After all success

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -4,18 +4,32 @@ node_js:
   - v7
 
 env:
-  - PARALLEL_NODE=lint
-  - PARALLEL_NODE=test
+  - PARALLEL_NODE=0
+  - PARALLEL_NODE=1
+  - PARALLEL_NODE=2
 
 script:
-  - npm run ${PARALLEL_NODE}
+  - node scripts/parallel-test
 
 after_success:
-  - curl -s https://codecov.io/bash | bash
-  - git config --global user.email "auto_deploy@circleci.com"
-  - git config --global user.name "CircleCI"
-  - echo -e "cepave\n${NPM_PASSWD}\nrwu@cepave.com" | npm login
-  - babel-node scripts/deploy.js
+  - |
+    declare exitCode
+
+    curl -sSL https://unpkg.com/travis-after-all | node
+    exitCode=$?
+
+    if [ $exitCode -eq 0 ]; then
+      echo "after_all_Succes"
+    fi
+
+    if [ $exitCode -eq 1 ]; then
+      echo "after_all_Failure"
+    fi
+#  - curl -s https://codecov.io/bash | bash
+#  - git config --global user.email "auto_deploy@circleci.com"
+#  - git config --global user.name "CircleCI"
+#  - echo -e "cepave\n${NPM_PASSWD}\nrwu@cepave.com" | npm login
+#  - babel-node scripts/deploy.js
 
 branches:
   except:
